baseURL = "https://liuange.github.io"
title = "Angela Liu"
theme = "etch"
languageCode = "en-US"
enableInlineShortcodes = true
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  description = "Angela Liu | Data Engineer"
  copyright = "Copyright © 2024 Angela Liu"
  dark = "off"
  highlight = true

[menu]
  [[menu.main]]
    identifier = "projects"
    name = "projects"
    title = "projects"
    url = "/projects/"
    weight = 10

  [[menu.main]]
    identifier = "about"
    name = "about"
    title = "about"
    url = "/about/"
    weight = 30

  [[menu.main]]
    identifier = "resume"
    name = "resume"
    title = "resume"
    url = "/resume/"
    weight = 20

  [[menu.main]]
    identifier = "github"
    name = "github"
    title = "github"
    url = "https://github.com/liuange"
    weight = 40

[permalinks]
  posts = "/:title/"

[markup.goldmark.renderer]
  # Allow HTML in Markdown
  unsafe = true

  [markup.tableOfContents]
    ordered = true
